ParkingApi/MVC/Controllers/MiastaController.cs
using BLL.IWorkServices;
using DAL.Entity;
using DAL.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace MVC.Controllers
{
    public class MiastaController : Controller
    {
        private IMiastoService miastoService;

        public MiastaController(IMiastoService miastoService)
        {
            this.miastoService = miastoService;
        }
        public async Task<IActionResult> Index()
        {
            var miasta = await miastoService.GetMiasta();
            ViewBag.Miasta = miasta;
            return View(miasta);
        }

        public async Task<IActionResult> Details(int id) 
        {
            if (id == null)
            {
                return NotFound();
            }

            var miasto = await miastoService.GetMiastoByIdDetails(id);

            if (miasto == null) {
                
                return NotFound();
            
            }

            return View(miasto);
        }

        public async Task<IActionResult> Create([Bind("Nazwa,Wojewodztwo")] Miasto miasto)
        {
            if (ModelState.IsValid)
            {
                await miastoService.AddMiasto(miasto);
                return RedirectToAction(nameof(Index));
            }
            return View(miasto);
        }

        public async Task<IActionResult> Edit(int id, [Bind("Id,Nazwa,Wojewodztwo")] Miasto miasto)
        {

            if (id != miasto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                await miastoService.UpdateMiasto(miasto);
                return RedirectToAction(nameof(Index));
            }
            
            return View(await miastoService.GetMiastoById(id));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var miasto = await miastoService.GetMiastoById(id);
            
            if (miasto != null)
            {
                await miastoService.DeleteMiasto(miasto);
                ViewBag.Miasto = miasto;
                return RedirectToAction(nameof(Index));
            }

            return View(miasto);
        }
    }
}

ParkingApi/MVC/Controllers/MiejscaController.cs
using BLL.IWorkServices;
using BLL.WorkServices;
using DAL.Entity;
using DAL.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MVC.Controllers
{
    public class MiejscaController : Controller
    {
        private IMiejsceService miejscaService;
        private IParkingService parkingService;

        public MiejscaController(IMiejsceService miejscaService, IParkingService parkingService)
        {
            this.miejscaService = miejscaService;
            this.parkingService = parkingService;
        }
        public async Task<IActionResult> Index()
        {
            var miejsca = await miejscaService.GetMiejsca();
            return View(miejsca);
        }

        public async Task<IActionResult> Details(int id) 
        {
            if (id == null)
            {
                return NotFound();
            }

            var miejsce = await miejscaService.GetMiejsceByIdDetails(id);

            if (miejsce == null)
            {

                return NotFound();

            }

            return View(miejsce);
        }

        public async Task<IActionResult> Create([Bind("ParkingId")] Miejsce miejsce)
        {
            if (ModelState.IsValid)
            {
                await miejscaService.AddMiejsce(miejsce);
                return RedirectToAction(nameof(Index));
            }

            Parking parking = new Parking();

            ViewData["IdParkingu"] = new SelectList(await parkingService.GetParkingi(), "Id", "Nazwa",miejsce.ParkingId);

            return View(miejsce);
        }

        public async Task<IActionResult> Edit(int id, [Bind("Id,ParkingId,MiejsceInwalidzkieId")] Miejsce miejsce)
        {
            if (id != miejsce.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                miejscaService.UpdateMiejsce(miejsce);
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdParkingu"] = new SelectList(await parkingService.GetParkingi(), "Id", "Nazwa", miejsce.ParkingId);

            return View(miejsce);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var miejsce = await miejscaService.GetMiejsceById(id);

            if (miejsce != null)
            {
                await miejscaService.DeleteMiejsce(miejsce);
                return RedirectToAction(nameof(Index));
            }

            return View(miejsce);
        }
    }
}

ParkingApi/MVC/Controllers/ParkingiController.cs
using BLL.IWorkServices;
using BLL.WorkServices;
using DAL.DataContext;
using DAL.Entity;
using DAL.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Host;
using Microsoft.EntityFrameworkCore;

namespace MVC.Controllers
{
    public class ParkingiController : Controller
    {
        private IParkingService parkingService;
        private IMiastoService miastoService;
        private IOpiekunService opiekunService;
        private IMiejsceService miejsceService;

        public ParkingiController(IParkingService parkingService, IMiastoService miastoService, IOpiekunService opiekunService,IMiejsceService miejsceService)
        {
            this.parkingService = parkingService;
            this.miastoService = miastoService;
            this.opiekunService = opiekunService;
            this.miejsceService = miejsceService;
        }


        public async Task<IActionResult> Index()
        {
            var parkingi = await parkingService.GetParkingi();
            return View(parkingi);
        }

        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parking = await parkingService.GetParkingiByIdDetails(id);

            if (parking == null)
            {

                return NotFound();

            }

            TempData["ID"] = id;
            return View(parking);
        }

        public async Task<IActionResult> Create([Bind("Adres,Nazwa,IdMiasta")] Parking parking)
        {
            if (ModelState.IsValid)
            {
                await parkingService.AddParking(parking);
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdMiasta"] = new SelectList(await miastoService.GetMiasta(), "Id", "Nazwa", parking.IdMiasta);
            return View(parking);
        }

        public async Task<IActionResult> DodajOpiekuna(int id, int opiekunId)
        {
            Parking parking = await parkingService.GetParkingiByIdDetails(id);
            Opiekun opiekun = await opiekunService.GetOpiekunById(opiekunId);
            ICollection<Opiekun> opiekunowie = new List<Opiekun>();
            parking.Opiekunowie = opiekunowie;

            if (ModelState.IsValid && opiekunId > 0)
            {
                parking.Opiekunowie.Add(opiekun);
                await parkingService.UpdateParking(parking);
                return RedirectToAction(nameof(Index));
            }

            ViewData["Opiekun"] = new SelectList(await opiekunService.GetOpiekunowie(), "Id", "Nazwisko");
            
            return View(parking);
        }

        public async Task<IActionResult> DodajMiejsca(int id, int ilosc)
        {
            Parking parking = await parkingService.GetParkingiByIdDetails(id);
            ICollection<Miejsce> miejsca = new List<Miejsce>();

            if (ModelState.IsValid && ilosc > 0)
            {
                for (int i = 0; i < ilosc; i++)
                {
                    var miejsce = new Miejsce
                    {
                        ParkingId = id,
                    };

                    await miejsceService.AddMiejsce(miejsce);
                }
                return RedirectToAction(nameof(Index));
            }

            return View(parking);
        }

        public async Task<IActionResult> UsunOpiekuna(int id)
        {
            int idParkingu = Convert.ToInt32(TempData["ID"]);

            TempData.Keep("ID");

            if (ModelState.IsValid)
            {
                await parkingService.UsunOpiekuna(id, idParkingu);
                return RedirectToAction(nameof(Index));
            }
           
            return View(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id, [Bind("Id,Nazwa,Adres,IdMiasta")] Parking parking)
        {
            if (id != parking.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                await parkingService.UpdateParking(parking);
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdMiasta"] = new SelectList(await miastoService.GetMiasta(), "Id", "Nazwa", parking.IdMiasta);
            return View(await parkingService.GetParkingiByIdDetails(id));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var parking = await parkingService.GetParkingiById(id);

            if (parking != null)
            {
                await parkingService.DeleteParking(parking);
                return RedirectToAction(nameof(Index));
            }

            return View(parking);
        }
    }
}

ParkingApi/MVC/Controllers/RezerwacjeController.cs
using BLL.IWorkServices;
using BLL.WorkServices;
using DAL.Entity;
using DAL.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using System.Data.Odbc;

namespace MVC.Controllers
{
    public class RezerwacjeController : Controller
    {
        private IRezerwacjeService rezerwacjeService;
        private IMiejsceService miejscaService;

        public RezerwacjeController(IRezerwacjeService rezerwacjeService,IMiejsceService miejscaService)
        {
            this.rezerwacjeService = rezerwacjeService;
            this.miejscaService = miejscaService;
        }

        public async Task<IActionResult> Index()
        {
            var rezerwacje = await rezerwacjeService.GetRezerwacje();
            return View(rezerwacje);
        }

        public async Task<IActionResult> Create([Bind("Od,Do,IdMiejsca,Imie,Nazwisko")] Rezerwacja rezerwacja)
        {
            ViewBag.Message = null;

            if (rezerwacja.IdMiejsca != null && rezerwacja.Od >= DateTime.Now && rezerwacja.Do > rezerwacja.Od)
            {
                if (await rezerwacjeService.CzyMoznaRezerwowac(rezerwacja.IdMiejsca, rezerwacja.Od, rezerwacja.Do))
                {
                    await rezerwacjeService.AddRezerwacja(rezerwacja);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.Message = "Ta data koliduje z inną rezerwacją dla tego miejsca";
                }
            }
            

            return View(rezerwacja);
        }

        public async Task<IActionResult> Edit(int id, [Bind("Id,Od,Do,IdMiejsca,Imie,Nazwisko")] Rezerwacja rezerwacja)
        {
            ViewBag.Message = null;

            if (rezerwacja.IdMiejsca != null && rezerwacja.Od >= DateTime.Now && rezerwacja.Do > rezerwacja.Od)
            {
                if (await rezerwacjeService.CzyMoznaRezerwowac(rezerwacja.IdMiejsca, rezerwacja.Od, rezerwacja.Do,rezerwacja.Id))
                {
                    await rezerwacjeService.UpdateRezerwacja(rezerwacja);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.Message = "Ta data koliduje z inną rezerwacją dla tego miejsca";
                }
            }

            //if (id != rezerwacja.Id)
            //{
            //    return NotFound();
            //}

            //if (ModelState.IsValid)
            //{

            //    await rezerwacjeService.UpdateRezerwacja(rezerwacja);
            //    return RedirectToAction(nameof(Index));
            //}
            return View(await rezerwacjeService.GetRezerwacjaByIdDetails(id));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var rezerwacja = await rezerwacjeService.GetRezerwacjaById(id);

            if (rezerwacja != null)
            {
                await rezerwacjeService.DeleteRezerwacja(rezerwacja);
                return RedirectToAction(nameof(Index));
            }

            return View(rezerwacja);
        }
    }
}

ParkingApi/MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] ParkingApi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
   @* <link rel="stylesheet" href="~/css/CssTheme.css" />*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @*<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">ParkingManage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Miasta" asp-action="Index">Miasta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Parkingi" asp-action="Index">Parkingi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Opiekunowie" asp-action="Index">Opiekunowie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Miejsca" asp-action="Index">Miejsca</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Inwalidzkie" asp-action="Index">Miejsca inwalidzkie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Rezerwacje" asp-action="Index">Rezerwacje</a>
                        </li>
                     </ul>
                </div>
            </div>
        </nav>*@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ParkingManage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Miasta" asp-action="Index">Miasta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parkingi" asp-action="Index">Parkingi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Opiekunowie" asp-action="Index">Opiekunowie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Miejsca" asp-action="Index">Miejsca</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inwalidzkie" asp-action="Index">Miejsca inwalidzkie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rezerwacje" asp-action="Index">Rezerwacje</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Konrad Bladziak & Michał Czajkowski 2023<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>